name: Node.js Deploy Pipeline

on: 
  push:
    branches:
      - production
  workflow_dispatch:
    inputs:
      runType:
        type: choice
        required: true
        description: ''
        default: 'デプロイ'
        options:
          - 'デプロイ'
          - 'アプリケーション 再起動'
          - 'アプリケーション 停止'
jobs:
  kill_process:
    runs-on: ubuntu-latest
    steps:
      - name: Update OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Down Process
        env:
          HOST: ${{secrets.EC2_HOST}}
          USER: ${{secrets.EC2_USER}}
          PRIVATE_KEY: ${{secrets.EC2_SSH_PRIVATE_KEY}}
        run:
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "pkill ^node$ &"
          
  deploy_and_start_process:
    if: github.event_name == 'push' || github.event.inputs.runType == 'デプロイ'
    needs: kill_process
    runs-on: ubuntu-latest

    steps:
      - name: Update OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl

      - name: Checkout code to production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Install Dependencies and Build
        env:
          NODE_ENV: production
        run:
          npm ci
          npm run build

      - name: Deploy to EC2
        env: 
          HOST: ${{secrets.EC2_HOST}}
          USER: ${{secrets.EC2_USER}}
          PRIVATE_KEY: ${{secrets.EC2_SSH_PRIVATE_KEY}}
        run:
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "rm -r -f /testgame && mkdir /home/ec2-user/testgame &"
          ssh -0 StrictHostKeyChecking=no -i private_key.pem $USER@HOST "mkdir -p /home/ec2-user/testgame-log &"
          echo "put -r ./dist ./testgame/dist" | sftp -i private_key.pem $USER@$HOST
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "volta install node@18.17.1 && npm ci --production --prefix /home/ec2-user/testgame"
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "NODE_ENV=production nohup npm run start --prefix /home/ec2-user/testgame > /home/ec2-user/testgame-log/nohup-$(date +%Y%m%d%H%M).log 2>&1 &"
          
  just_start_process:
    if: github.event.inputs.runType == 'アプリケーション 再起動'
    needs: kill_process
    runs-on: ubuntu-latest
    steps:
      - name: Update OpenSSL
        run: sudo apt-get update && sudo apt-get install -y openssl
        
      - name: Restart Application   
        env:
          HOST: ${{secrets.EC2_HOST}}
          USER: ${{secrets.EC2_USER}}
          PRIVATE_KEY: ${{secrets.EC2_SSH_PRIVATE_KEY}}
        run:
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST "NODE_ENV=production nohup nom run start --prefix /home/ec2-user/testgame > /home/ec2-user/testgame-log/nohup-$(date +%Y%m%d%H%M).log 2>&1 &"
