name: EC2 auto deploy

on: 
  pull_request:
    branches: [ main ]
    types: [closed]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Public IP Install
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Checkout
        uses: actions/checkout@v2

      - name: AWS CLI Install
        run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" &&
             unzip awscliv2.zip &&
             sudo ./aws/install --update &&
             aws --version

      - name: AWS set Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy
        run:
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
          echo "${{ secrets.GIT_PRIVATE_KEY }}" > private_key
          chmod 777 private_key
          ssh -oStrictHostKeyChecking=no ${{ secrets.EC2_USER_NAME }}@${{ secrets.EC2_HOST_NAME }} -i private_key "cd /var/www/html/test && git fetch --prune && git checkout main && git pull origin main"
          ssh ec2 revoke-security-group-ingress --group-id ${{ secrets.EC2_SECURITY_GROUP_ID }} --protocol --port 22 -cidr ${{ steps.ip.outputs.ipv4 }}/32
        
        
    

